
### 회원가입 ( 고객 )
POST http://localhost:8001/signUp/customer
Content-Type: application/json


### 이메일 인증 ( 고객 )
POST http://localhost:8001/signUp/customer

### 로그인 ( 고객 )

### 회원 정보 조회 ( 고객 )

### 잔액 변경 ( 고객 )

################################

### 회원가입 ( 셀러 )

### 로그인 ( 셀러 )


